#ifndef RCUDD
#define RCUDD

#ifndef R_NO_REMAP
#define R_NO_REMAP
#endif

#include <Rinternals.h>

extern "C" SEXP bdd_remaining_literals(SEXP expr_in);
extern "C" SEXP bdd_restrict_chain(SEXP exprs_in, SEXP additional_constraints_in);
extern "C" SEXP c_cudd_new();
extern "C" SEXP c_cudd_read_size(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_cache_slots(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_cache_used_slots(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_cache_lookups(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_cache_hits(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_min_hit(SEXP mgr_ptr);
extern "C" SEXP c_cudd_set_min_hit(SEXP mgr_ptr, SEXP hr);
extern "C" SEXP c_cudd_read_loose_up_to(SEXP mgr_ptr);
extern "C" SEXP c_cudd_set_loose_up_to(SEXP mgr_ptr, SEXP lut);
extern "C" SEXP c_cudd_make_verbose(SEXP mgr_ptr);
extern "C" SEXP c_cudd_make_terse(SEXP mgr_ptr);
extern "C" SEXP c_cudd_is_verbose(SEXP mgr_ptr);
extern "C" SEXP c_cudd_info(SEXP mgr_ptr);
extern "C" SEXP c_cudd_push_variable_name(SEXP mgr_ptr, SEXP name);
extern "C" SEXP c_cudd_clear_variable_names(SEXP mgr_ptr);
extern "C" SEXP c_cudd_get_variable_name(SEXP mgr_ptr, SEXP index);
extern "C" SEXP c_cudd_read_node_count(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_zdd_size(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_reorderings(SEXP mgr_ptr);
extern "C" SEXP c_cudd_bdd_one(SEXP mgr_ptr);
extern "C" SEXP c_cudd_bdd_zero(SEXP mgr_ptr);
extern "C" SEXP c_cudd_bdd_var(SEXP mgr_ptr, SEXP index);
extern "C" SEXP c_cudd_add_one(SEXP mgr_ptr);
extern "C" SEXP c_cudd_add_zero(SEXP mgr_ptr);
extern "C" SEXP c_cudd_add_var(SEXP mgr_ptr, SEXP index);
extern "C" SEXP c_cudd_zdd_one(SEXP mgr_ptr, SEXP index);
extern "C" SEXP c_cudd_zdd_zero(SEXP mgr_ptr);
extern "C" SEXP c_cudd_zdd_var(SEXP mgr_ptr, SEXP index);
extern "C" SEXP c_cudd_bdd_not(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_and(SEXP lhs_ptr, SEXP rhs_ptr);
extern "C" SEXP c_cudd_bdd_or(SEXP lhs_ptr, SEXP rhs_ptr);
extern "C" SEXP c_cudd_bdd_xor(SEXP lhs_ptr, SEXP rhs_ptr);
extern "C" SEXP c_cudd_bdd_restrict(SEXP bdd_ptr, SEXP constraint_ptr);
extern "C" SEXP c_cudd_bdd_ite_formula(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_print(SEXP bdd_ptr, SEXP nvars, SEXP verbosity);
extern "C" SEXP c_cudd_bdd_summary(SEXP bdd_ptr, SEXP nvars, SEXP mode);
extern "C" SEXP c_cudd_bdd_apa_print_minterm(SEXP bdd_ptr, SEXP nvars);
extern "C" SEXP c_cudd_bdd_apa_print_minterm_exp(SEXP bdd_ptr, SEXP nvars, SEXP precision);
extern "C" SEXP c_cudd_bdd_ldbl_count_minterm(SEXP bdd_ptr, SEXP nvars);
extern "C" SEXP c_cudd_bdd_shortest_path(SEXP bdd_ptr, SEXP weight);
extern "C" SEXP c_cudd_bdd_largest_cube(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_shortest_length(SEXP bdd_ptr, SEXP weight);
extern "C" SEXP c_cudd_bdd_equiv_dc(SEXP bdd_ptr, SEXP g_ptr, SEXP d_ptr);
extern "C" SEXP c_cudd_bdd_cof_minterm(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_is_one(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_is_cube(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_find_essential(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_print_two_literal_clauses(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_count_minterm(SEXP bdd_ptr, SEXP nvars);
extern "C" SEXP c_cudd_bdd_count_path(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_support(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_support_size(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_support_indices(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_classify_support(SEXP bdd_ptr, SEXP other_ptr);
extern "C" SEXP c_cudd_bdd_count_leaves(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_density(SEXP bdd_ptr, SEXP nvars);
extern "C" SEXP c_cudd_bdd_under_approx(SEXP bdd_ptr, SEXP num_vars, SEXP threshold, SEXP safe, SEXP quality);
extern "C" SEXP c_cudd_bdd_over_approx(SEXP bdd_ptr, SEXP num_vars, SEXP threshold, SEXP safe, SEXP quality);
extern "C" SEXP c_cudd_bdd_remap_under_approx(SEXP bdd_ptr, SEXP num_vars, SEXP threshold, SEXP quality);
extern "C" SEXP c_cudd_bdd_remap_over_approx(SEXP bdd_ptr, SEXP num_vars, SEXP threshold, SEXP quality);
extern "C" SEXP c_cudd_bdd_biased_under_approx(SEXP bdd_ptr, SEXP bias_ptr, SEXP num_vars, SEXP threshold, SEXP quality1, SEXP quality0);
extern "C" SEXP c_cudd_bdd_biased_over_approx(SEXP bdd_ptr, SEXP bias_ptr, SEXP num_vars, SEXP threshold, SEXP quality1, SEXP quality0);
extern "C" SEXP c_cudd_bdd_clipping_and(SEXP bdd_ptr, SEXP other_ptr, SEXP max_depth, SEXP direction);
extern "C" SEXP c_cudd_bdd_clipping_and_abstract(SEXP bdd_ptr, SEXP other_ptr, SEXP cube_ptr, SEXP max_depth, SEXP direction);
extern "C" SEXP c_cudd_bdd_var_are_symmetric(SEXP bdd_ptr, SEXP index1, SEXP index2);
extern "C" SEXP c_cudd_bdd_adj_permute_x(SEXP bdd_ptr, SEXP x_list);
extern "C" SEXP c_cudd_bdd_is_var_essential(SEXP bdd_ptr, SEXP index, SEXP phase);
extern "C" SEXP c_cudd_bdd_np_and(SEXP bdd_ptr, SEXP other_ptr);
extern "C" SEXP c_cudd_bdd_constrain_decomp(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_char_to_vect(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_leq_unless(SEXP bdd_ptr, SEXP g_ptr, SEXP d_ptr);
extern "C" SEXP c_cudd_bdd_maximally_expand(SEXP bdd_ptr, SEXP ub_ptr, SEXP f_ptr);
extern "C" SEXP c_cudd_bdd_largest_prime_unate(SEXP bdd_ptr, SEXP phases_ptr);
extern "C" SEXP c_cudd_bdd_solve_eqn(SEXP bdd_ptr, SEXP y_ptr, SEXP n);
extern "C" SEXP c_cudd_bdd_verify_sol(SEXP bdd_ptr, SEXP g_list, SEXP y_index);
extern "C" SEXP c_cudd_bdd_split_set(SEXP bdd_ptr, SEXP x_vars, SEXP m);
extern "C" SEXP c_cudd_bdd_estimate_cofactor(SEXP bdd_ptr, SEXP index, SEXP phase);
extern "C" SEXP c_cudd_bdd_estimate_cofactor_simple(SEXP bdd_ptr, SEXP index);
extern "C" SEXP c_cudd_bdd_zdd_isop(SEXP bdd_ptr, SEXP upper_ptr);
extern "C" SEXP c_cudd_bdd_transfer(SEXP bdd_ptr, SEXP mgr_ptr);
extern "C" SEXP c_cudd_bdd_is_zero(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_is_var(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_leq(SEXP lhs_ptr, SEXP rhs_ptr);
extern "C" SEXP c_cudd_bdd_and_abstract(SEXP bdd_ptr, SEXP other_ptr, SEXP cube_ptr, SEXP limit);
extern "C" SEXP c_cudd_bdd_exist_abstract(SEXP bdd_ptr, SEXP cube_ptr, SEXP limit);
extern "C" SEXP c_cudd_bdd_univ_abstract(SEXP bdd_ptr, SEXP cube_ptr);
extern "C" SEXP c_cudd_bdd_xor_exist_abstract(SEXP bdd_ptr, SEXP other_ptr, SEXP cube_ptr);
extern "C" SEXP c_cudd_bdd_boolean_diff(SEXP bdd_ptr, SEXP index);
extern "C" SEXP c_cudd_bdd_var_is_dependent(SEXP bdd_ptr, SEXP var_ptr);
extern "C" SEXP c_cudd_bdd_correlation(SEXP bdd_ptr, SEXP other_ptr);
extern "C" SEXP c_cudd_bdd_correlation_weights(SEXP bdd_ptr, SEXP other_ptr, SEXP prob);
extern "C" SEXP c_cudd_bdd_xor_method(SEXP bdd_ptr, SEXP other_ptr);
extern "C" SEXP c_cudd_bdd_ite(SEXP bdd_ptr, SEXP g_ptr, SEXP h_ptr, SEXP limit);
extern "C" SEXP c_cudd_bdd_ite_constant(SEXP bdd_ptr, SEXP g_ptr, SEXP h_ptr);
extern "C" SEXP c_cudd_bdd_intersect(SEXP bdd_ptr, SEXP other_ptr);
extern "C" SEXP c_cudd_bdd_and_limit(SEXP bdd_ptr, SEXP other_ptr, SEXP limit);
extern "C" SEXP c_cudd_bdd_or_limit(SEXP bdd_ptr, SEXP other_ptr, SEXP limit);
extern "C" SEXP c_cudd_bdd_nand(SEXP bdd_ptr, SEXP other_ptr);
extern "C" SEXP c_cudd_bdd_nor(SEXP bdd_ptr, SEXP other_ptr);
extern "C" SEXP c_cudd_bdd_xnor(SEXP bdd_ptr, SEXP other_ptr, SEXP limit);
extern "C" SEXP c_cudd_bdd_cofactor(SEXP bdd_ptr, SEXP other_ptr);
extern "C" SEXP c_cudd_bdd_constrain(SEXP bdd_ptr, SEXP other_ptr);
extern "C" SEXP c_cudd_bdd_compose(SEXP bdd_ptr, SEXP other_ptr, SEXP index);
extern "C" SEXP c_cudd_bdd_permute(SEXP bdd_ptr, SEXP permut);
extern "C" SEXP c_cudd_bdd_swap_variables(SEXP bdd_ptr, SEXP x_list, SEXP y_list);
extern "C" SEXP c_cudd_bdd_vector_compose(SEXP bdd_ptr, SEXP vector_list);
extern "C" SEXP c_cudd_bdd_approx_conj_decomp(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_approx_disj_decomp(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_iter_conj_decomp(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_iter_disj_decomp(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_gen_conj_decomp(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_gen_disj_decomp(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_var_conj_decomp(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_var_disj_decomp(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_li_compaction(SEXP bdd_ptr, SEXP other_ptr);
extern "C" SEXP c_cudd_bdd_squeeze(SEXP bdd_ptr, SEXP other_ptr);
extern "C" SEXP c_cudd_bdd_interpolate(SEXP bdd_ptr, SEXP other_ptr);
extern "C" SEXP c_cudd_bdd_minimize(SEXP bdd_ptr, SEXP other_ptr);
extern "C" SEXP c_cudd_bdd_subset_compress(SEXP bdd_ptr, SEXP nvars, SEXP threshold);
extern "C" SEXP c_cudd_bdd_superset_compress(SEXP bdd_ptr, SEXP nvars, SEXP threshold);
extern "C" SEXP c_cudd_bdd_literal_set_intersection(SEXP bdd_ptr, SEXP other_ptr);
extern "C" SEXP c_cudd_bdd_c_projection(SEXP bdd_ptr, SEXP other_ptr);
extern "C" SEXP c_cudd_bdd_min_hamming_dist(SEXP bdd_ptr, SEXP minterm, SEXP upper_bound);
extern "C" SEXP c_cudd_bdd_eval(SEXP bdd_ptr, SEXP inputs);
extern "C" SEXP c_cudd_bdd_decreasing(SEXP bdd_ptr, SEXP index);
extern "C" SEXP c_cudd_bdd_increasing(SEXP bdd_ptr, SEXP index);
extern "C" SEXP c_cudd_bdd_make_prime(SEXP bdd_ptr, SEXP other_ptr);
extern "C" SEXP c_cudd_bdd_subset_heavy_branch(SEXP bdd_ptr, SEXP num_vars, SEXP threshold);
extern "C" SEXP c_cudd_bdd_superset_heavy_branch(SEXP bdd_ptr, SEXP num_vars, SEXP threshold);
extern "C" SEXP c_cudd_bdd_subset_short_paths(SEXP bdd_ptr, SEXP num_vars, SEXP threshold, SEXP hardlimit);
extern "C" SEXP c_cudd_bdd_superset_short_paths(SEXP bdd_ptr, SEXP num_vars, SEXP threshold, SEXP hardlimit);
extern "C" SEXP c_cudd_bdd_print_cover(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_print_cover_with_cube(SEXP bdd_ptr, SEXP cube_ptr);
extern "C" SEXP c_cudd_bdd_pick_one_cube(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_pick_one_minterm(SEXP bdd_ptr, SEXP vars_list);
extern "C" SEXP c_cudd_bdd_isop(SEXP bdd_ptr, SEXP upper_ptr);
extern "C" SEXP c_cudd_bdd_port_to_zdd(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_factored_form_string(SEXP bdd_ptr);
extern "C" SEXP c_cudd_bdd_print_factored_form(SEXP bdd_ptr);
extern "C" SEXP c_cudd_add_times(SEXP lhs_ptr, SEXP rhs_ptr);
extern "C" SEXP c_cudd_add_plus(SEXP lhs_ptr, SEXP rhs_ptr);
extern "C" SEXP c_cudd_zdd_intersect(SEXP lhs_ptr, SEXP rhs_ptr);
extern "C" SEXP c_cudd_zdd_union(SEXP lhs_ptr, SEXP rhs_ptr);
extern "C" SEXP c_cudd_bdd_to_add(SEXP bdd_ptr);
extern "C" SEXP c_cudd_add_to_bdd(SEXP add_ptr);
extern "C" SEXP c_cudd_bdd_to_zdd(SEXP bdd_ptr);
extern "C" SEXP c_cudd_zdd_to_bdd(SEXP zdd_ptr);
extern "C" SEXP c_cudd_bdd_epd_print_minterm(SEXP bdd_ptr, SEXP nvars);
extern "C" SEXP c_cudd_add_epd_print_minterm(SEXP add_ptr, SEXP nvars);
extern "C" SEXP c_cudd_bdd_print_minterm(SEXP bdd_ptr);
extern "C" SEXP c_cudd_add_print_minterm(SEXP add_ptr);
extern "C" SEXP c_cudd_zdd_print_minterm(SEXP zdd_ptr);
extern "C" SEXP c_cudd_bdd_truth_table(SEXP bdd_ptr, SEXP nvars);
extern "C" SEXP c_cudd_bdd_print_debug(SEXP bdd_ptr, SEXP nvars, SEXP verbosity);
extern "C" SEXP c_cudd_bdd_dump_dot(SEXP bdd_ptr);
extern "C" SEXP c_cudd_read_start_time(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_elapsed_time(SEXP mgr_ptr);
extern "C" SEXP c_cudd_set_start_time(SEXP mgr_ptr, SEXP st);
extern "C" SEXP c_cudd_reset_start_time(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_time_limit(SEXP mgr_ptr);
extern "C" SEXP c_cudd_set_time_limit(SEXP mgr_ptr, SEXP tl);
extern "C" SEXP c_cudd_update_time_limit(SEXP mgr_ptr);
extern "C" SEXP c_cudd_increase_time_limit(SEXP mgr_ptr, SEXP inc);
extern "C" SEXP c_cudd_unset_time_limit(SEXP mgr_ptr);
extern "C" SEXP c_cudd_time_limited(SEXP mgr_ptr);
extern "C" SEXP c_cudd_autodyn_enable(SEXP mgr_ptr, SEXP method);
extern "C" SEXP c_cudd_autodyn_disable(SEXP mgr_ptr);
extern "C" SEXP c_cudd_reordering_status(SEXP mgr_ptr);
extern "C" SEXP c_cudd_autodyn_enable_zdd(SEXP mgr_ptr, SEXP method);
extern "C" SEXP c_cudd_autodyn_disable_zdd(SEXP mgr_ptr);
extern "C" SEXP c_cudd_reordering_status_zdd(SEXP mgr_ptr);
extern "C" SEXP c_cudd_reduce_heap(SEXP mgr_ptr, SEXP heuristic, SEXP minsize);
extern "C" SEXP c_cudd_zdd_realignment_enabled(SEXP mgr_ptr);
extern "C" SEXP c_cudd_zdd_realign_enable(SEXP mgr_ptr);
extern "C" SEXP c_cudd_zdd_realign_disable(SEXP mgr_ptr);
extern "C" SEXP c_cudd_bdd_realignment_enabled(SEXP mgr_ptr);
extern "C" SEXP c_cudd_bdd_realign_enable(SEXP mgr_ptr);
extern "C" SEXP c_cudd_bdd_realign_disable(SEXP mgr_ptr);
extern "C" SEXP c_cudd_background(SEXP mgr_ptr);
extern "C" SEXP c_cudd_set_background(SEXP mgr_ptr, SEXP add_ptr);
extern "C" SEXP c_cudd_read_max_cache(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_max_cache_hard(SEXP mgr_ptr);
extern "C" SEXP c_cudd_set_max_cache_hard(SEXP mgr_ptr, SEXP mc);
extern "C" SEXP c_cudd_read_slots(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_keys(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_dead(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_min_dead(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_max_reorderings(SEXP mgr_ptr);
extern "C" SEXP c_cudd_set_max_reorderings(SEXP mgr_ptr, SEXP mr);
extern "C" SEXP c_cudd_read_reordering_time(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_garbage_collections(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_garbage_collection_time(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_sift_max_var(SEXP mgr_ptr);
extern "C" SEXP c_cudd_set_sift_max_var(SEXP mgr_ptr, SEXP smv);
extern "C" SEXP c_cudd_read_sift_max_swap(SEXP mgr_ptr);
extern "C" SEXP c_cudd_set_sift_max_swap(SEXP mgr_ptr, SEXP sms);
extern "C" SEXP c_cudd_read_max_growth(SEXP mgr_ptr);
extern "C" SEXP c_cudd_set_max_growth(SEXP mgr_ptr, SEXP mg);
extern "C" SEXP c_cudd_read_perm(SEXP mgr_ptr, SEXP i);
extern "C" SEXP c_cudd_read_perm_zdd(SEXP mgr_ptr, SEXP i);
extern "C" SEXP c_cudd_read_inv_perm(SEXP mgr_ptr, SEXP i);
extern "C" SEXP c_cudd_read_inv_perm_zdd(SEXP mgr_ptr, SEXP i);
extern "C" SEXP c_cudd_read_vars(SEXP mgr_ptr, SEXP i);
extern "C" SEXP c_cudd_read_epsilon(SEXP mgr_ptr);
extern "C" SEXP c_cudd_set_epsilon(SEXP mgr_ptr, SEXP ep);
extern "C" SEXP c_cudd_read_groupcheck(SEXP mgr_ptr);
extern "C" SEXP c_cudd_set_groupcheck(SEXP mgr_ptr, SEXP gc);
extern "C" SEXP c_cudd_garbage_collection_enabled(SEXP mgr_ptr);
extern "C" SEXP c_cudd_enable_garbage_collection(SEXP mgr_ptr);
extern "C" SEXP c_cudd_disable_garbage_collection(SEXP mgr_ptr);
extern "C" SEXP c_cudd_dead_are_counted(SEXP mgr_ptr);
extern "C" SEXP c_cudd_turn_on_count_dead(SEXP mgr_ptr);
extern "C" SEXP c_cudd_turn_off_count_dead(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_recomb(SEXP mgr_ptr);
extern "C" SEXP c_cudd_set_recomb(SEXP mgr_ptr, SEXP recomb);
extern "C" SEXP c_cudd_read_symmviolation(SEXP mgr_ptr);
extern "C" SEXP c_cudd_set_symmviolation(SEXP mgr_ptr, SEXP symm);
extern "C" SEXP c_cudd_read_arcviolation(SEXP mgr_ptr);
extern "C" SEXP c_cudd_set_arcviolation(SEXP mgr_ptr, SEXP arc);
extern "C" SEXP c_cudd_read_population_size(SEXP mgr_ptr);
extern "C" SEXP c_cudd_set_population_size(SEXP mgr_ptr, SEXP pop);
extern "C" SEXP c_cudd_read_number_xovers(SEXP mgr_ptr);
extern "C" SEXP c_cudd_set_number_xovers(SEXP mgr_ptr, SEXP xovers);
extern "C" SEXP c_cudd_read_order_randomization(SEXP mgr_ptr);
extern "C" SEXP c_cudd_set_order_randomization(SEXP mgr_ptr, SEXP factor);
extern "C" SEXP c_cudd_read_memory_in_use(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_peak_node_count(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_node_count_current(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_node_count_zdd(SEXP mgr_ptr);
extern "C" SEXP c_cudd_enable_reordering_reporting(SEXP mgr_ptr);
extern "C" SEXP c_cudd_disable_reordering_reporting(SEXP mgr_ptr);
extern "C" SEXP c_cudd_reordering_reporting(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_error_code(SEXP mgr_ptr);
extern "C" SEXP c_cudd_clear_error_code(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_next_reordering(SEXP mgr_ptr);
extern "C" SEXP c_cudd_set_next_reordering(SEXP mgr_ptr, SEXP nr);
extern "C" SEXP c_cudd_read_swap_steps(SEXP mgr_ptr);
extern "C" SEXP c_cudd_read_max_live(SEXP mgr_ptr);
extern "C" SEXP c_cudd_set_max_live(SEXP mgr_ptr, SEXP max_live);
extern "C" SEXP c_cudd_read_max_memory(SEXP mgr_ptr);
extern "C" SEXP c_cudd_set_max_memory(SEXP mgr_ptr, SEXP max_mem);
extern "C" SEXP c_cudd_bdd_bind_var(SEXP mgr_ptr, SEXP index);
extern "C" SEXP c_cudd_bdd_unbind_var(SEXP mgr_ptr, SEXP index);
extern "C" SEXP c_cudd_bdd_var_is_bound(SEXP mgr_ptr, SEXP index);

#ifdef __cplusplus
#include <string>
#include <unordered_map>
#include <vector>
#include "cuddObj.hh"

namespace rcudd {
BDD parse_bdd_expression(const std::string &expr,
                         Cudd &mgr,
                         std::unordered_map<std::string, unsigned int> &var_idx,
                         std::vector<std::string> &idx_to_name,
                         std::vector<std::string> *encountered_vars = nullptr);
}
#endif

#endif
