#include "rcudd.h"
#include <R.h>
#include <Rinternals.h>
#include <R_ext/Rdynload.h>
#include <R_ext/Visibility.h>

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"c_cudd_new", (DL_FUNC) &c_cudd_new, 0},
    {"c_cudd_read_size", (DL_FUNC) &c_cudd_read_size, 1},
    {"c_cudd_read_cache_slots", (DL_FUNC) &c_cudd_read_cache_slots, 1},
    {"c_cudd_read_cache_used_slots", (DL_FUNC) &c_cudd_read_cache_used_slots, 1},
    {"c_cudd_read_cache_lookups", (DL_FUNC) &c_cudd_read_cache_lookups, 1},
    {"c_cudd_read_cache_hits", (DL_FUNC) &c_cudd_read_cache_hits, 1},
    {"c_cudd_read_min_hit", (DL_FUNC) &c_cudd_read_min_hit, 1},
    {"c_cudd_set_min_hit", (DL_FUNC) &c_cudd_set_min_hit, 2},
    {"c_cudd_read_loose_up_to", (DL_FUNC) &c_cudd_read_loose_up_to, 1},
    {"c_cudd_set_loose_up_to", (DL_FUNC) &c_cudd_set_loose_up_to, 2},
    {"c_cudd_make_verbose", (DL_FUNC) &c_cudd_make_verbose, 1},
    {"c_cudd_make_terse", (DL_FUNC) &c_cudd_make_terse, 1},
    {"c_cudd_is_verbose", (DL_FUNC) &c_cudd_is_verbose, 1},
    {"c_cudd_info", (DL_FUNC) &c_cudd_info, 1},
    {"c_cudd_push_variable_name", (DL_FUNC) &c_cudd_push_variable_name, 2},
    {"c_cudd_clear_variable_names", (DL_FUNC) &c_cudd_clear_variable_names, 1},
    {"c_cudd_get_variable_name", (DL_FUNC) &c_cudd_get_variable_name, 2},
    {"c_cudd_read_node_count", (DL_FUNC) &c_cudd_read_node_count, 1},
    {"c_cudd_read_zdd_size", (DL_FUNC) &c_cudd_read_zdd_size, 1},
    {"c_cudd_read_reorderings", (DL_FUNC) &c_cudd_read_reorderings, 1},
    {"c_cudd_bdd_one", (DL_FUNC) &c_cudd_bdd_one, 1},
    {"c_cudd_bdd_zero", (DL_FUNC) &c_cudd_bdd_zero, 1},
    {"c_cudd_bdd_var", (DL_FUNC) &c_cudd_bdd_var, 2},
    {"c_cudd_add_one", (DL_FUNC) &c_cudd_add_one, 1},
    {"c_cudd_add_zero", (DL_FUNC) &c_cudd_add_zero, 1},
    {"c_cudd_add_var", (DL_FUNC) &c_cudd_add_var, 2},
    {"c_cudd_zdd_one", (DL_FUNC) &c_cudd_zdd_one, 2},
    {"c_cudd_zdd_zero", (DL_FUNC) &c_cudd_zdd_zero, 1},
    {"c_cudd_zdd_var", (DL_FUNC) &c_cudd_zdd_var, 2},
    {"c_cudd_bdd_not", (DL_FUNC) &c_cudd_bdd_not, 1},
    {"c_cudd_bdd_and", (DL_FUNC) &c_cudd_bdd_and, 2},
    {"c_cudd_bdd_or", (DL_FUNC) &c_cudd_bdd_or, 2},
    {"c_cudd_bdd_xor", (DL_FUNC) &c_cudd_bdd_xor, 2},
    {"c_cudd_add_times", (DL_FUNC) &c_cudd_add_times, 2},
    {"c_cudd_add_plus", (DL_FUNC) &c_cudd_add_plus, 2},
    {"c_cudd_zdd_intersect", (DL_FUNC) &c_cudd_zdd_intersect, 2},
    {"c_cudd_zdd_union", (DL_FUNC) &c_cudd_zdd_union, 2},
    {"c_cudd_bdd_to_add", (DL_FUNC) &c_cudd_bdd_to_add, 1},
    {"c_cudd_add_to_bdd", (DL_FUNC) &c_cudd_add_to_bdd, 1},
    {"c_cudd_bdd_to_zdd", (DL_FUNC) &c_cudd_bdd_to_zdd, 1},
    {"c_cudd_zdd_to_bdd", (DL_FUNC) &c_cudd_zdd_to_bdd, 1},
    {"c_cudd_bdd_epd_print_minterm", (DL_FUNC) &c_cudd_bdd_epd_print_minterm, 2},
    {"c_cudd_add_epd_print_minterm", (DL_FUNC) &c_cudd_add_epd_print_minterm, 2},
    {"c_cudd_bdd_print_minterm", (DL_FUNC) &c_cudd_bdd_print_minterm, 1},
    {"c_cudd_add_print_minterm", (DL_FUNC) &c_cudd_add_print_minterm, 1},
    {"c_cudd_zdd_print_minterm", (DL_FUNC) &c_cudd_zdd_print_minterm, 1},
    {"c_cudd_bdd_print_debug", (DL_FUNC) &c_cudd_bdd_print_debug, 3},
    {"c_cudd_bdd_dump_dot", (DL_FUNC) &c_cudd_bdd_dump_dot, 1},
    {"c_cudd_read_start_time", (DL_FUNC) &c_cudd_read_start_time, 1},
    {"c_cudd_read_elapsed_time", (DL_FUNC) &c_cudd_read_elapsed_time, 1},
    {"c_cudd_set_start_time", (DL_FUNC) &c_cudd_set_start_time, 2},
    {"c_cudd_reset_start_time", (DL_FUNC) &c_cudd_reset_start_time, 1},
    {"c_cudd_read_time_limit", (DL_FUNC) &c_cudd_read_time_limit, 1},
    {"c_cudd_set_time_limit", (DL_FUNC) &c_cudd_set_time_limit, 2},
    {"c_cudd_update_time_limit", (DL_FUNC) &c_cudd_update_time_limit, 1},
    {"c_cudd_increase_time_limit", (DL_FUNC) &c_cudd_increase_time_limit, 2},
    {"c_cudd_unset_time_limit", (DL_FUNC) &c_cudd_unset_time_limit, 1},
    {"c_cudd_time_limited", (DL_FUNC) &c_cudd_time_limited, 1},
    {"c_cudd_autodyn_enable", (DL_FUNC) &c_cudd_autodyn_enable, 2},
    {"c_cudd_autodyn_disable", (DL_FUNC) &c_cudd_autodyn_disable, 1},
    {"c_cudd_reordering_status", (DL_FUNC) &c_cudd_reordering_status, 1},
    {"c_cudd_autodyn_enable_zdd", (DL_FUNC) &c_cudd_autodyn_enable_zdd, 2},
    {"c_cudd_autodyn_disable_zdd", (DL_FUNC) &c_cudd_autodyn_disable_zdd, 1},
    {"c_cudd_reordering_status_zdd", (DL_FUNC) &c_cudd_reordering_status_zdd, 1},
    {"c_cudd_zdd_realignment_enabled", (DL_FUNC) &c_cudd_zdd_realignment_enabled, 1},
    {"c_cudd_zdd_realign_enable", (DL_FUNC) &c_cudd_zdd_realign_enable, 1},
    {"c_cudd_zdd_realign_disable", (DL_FUNC) &c_cudd_zdd_realign_disable, 1},
    {"c_cudd_bdd_realignment_enabled", (DL_FUNC) &c_cudd_bdd_realignment_enabled, 1},
    {"c_cudd_bdd_realign_enable", (DL_FUNC) &c_cudd_bdd_realign_enable, 1},
    {"c_cudd_bdd_realign_disable", (DL_FUNC) &c_cudd_bdd_realign_disable, 1},
    {"c_cudd_background", (DL_FUNC) &c_cudd_background, 1},
    {"c_cudd_set_background", (DL_FUNC) &c_cudd_set_background, 2},
    {"c_cudd_read_max_cache", (DL_FUNC) &c_cudd_read_max_cache, 1},
    {"c_cudd_read_max_cache_hard", (DL_FUNC) &c_cudd_read_max_cache_hard, 1},
    {"c_cudd_set_max_cache_hard", (DL_FUNC) &c_cudd_set_max_cache_hard, 2},
    {"c_cudd_read_slots", (DL_FUNC) &c_cudd_read_slots, 1},
    {"c_cudd_read_keys", (DL_FUNC) &c_cudd_read_keys, 1},
    {"c_cudd_read_dead", (DL_FUNC) &c_cudd_read_dead, 1},
    {"c_cudd_read_min_dead", (DL_FUNC) &c_cudd_read_min_dead, 1},
    {"c_cudd_read_max_reorderings", (DL_FUNC) &c_cudd_read_max_reorderings, 1},
    {"c_cudd_set_max_reorderings", (DL_FUNC) &c_cudd_set_max_reorderings, 2},
    {"c_cudd_read_reordering_time", (DL_FUNC) &c_cudd_read_reordering_time, 1},
    {"c_cudd_read_garbage_collections", (DL_FUNC) &c_cudd_read_garbage_collections, 1},
    {"c_cudd_read_garbage_collection_time", (DL_FUNC) &c_cudd_read_garbage_collection_time, 1},
    {"c_cudd_read_sift_max_var", (DL_FUNC) &c_cudd_read_sift_max_var, 1},
    {"c_cudd_set_sift_max_var", (DL_FUNC) &c_cudd_set_sift_max_var, 2},
    {"c_cudd_read_sift_max_swap", (DL_FUNC) &c_cudd_read_sift_max_swap, 1},
    {"c_cudd_set_sift_max_swap", (DL_FUNC) &c_cudd_set_sift_max_swap, 2},
    {"c_cudd_read_max_growth", (DL_FUNC) &c_cudd_read_max_growth, 1},
    {"c_cudd_set_max_growth", (DL_FUNC) &c_cudd_set_max_growth, 2},
    {"c_cudd_read_perm", (DL_FUNC) &c_cudd_read_perm, 2},
    {"c_cudd_read_perm_zdd", (DL_FUNC) &c_cudd_read_perm_zdd, 2},
    {"c_cudd_read_inv_perm", (DL_FUNC) &c_cudd_read_inv_perm, 2},
    {"c_cudd_read_inv_perm_zdd", (DL_FUNC) &c_cudd_read_inv_perm_zdd, 2},
    {"c_cudd_read_vars", (DL_FUNC) &c_cudd_read_vars, 2},
    {"c_cudd_read_epsilon", (DL_FUNC) &c_cudd_read_epsilon, 1},
    {"c_cudd_set_epsilon", (DL_FUNC) &c_cudd_set_epsilon, 2},
    {"c_cudd_read_groupcheck", (DL_FUNC) &c_cudd_read_groupcheck, 1},
    {"c_cudd_set_groupcheck", (DL_FUNC) &c_cudd_set_groupcheck, 2},
    {"c_cudd_garbage_collection_enabled", (DL_FUNC) &c_cudd_garbage_collection_enabled, 1},
    {"c_cudd_enable_garbage_collection", (DL_FUNC) &c_cudd_enable_garbage_collection, 1},
    {"c_cudd_disable_garbage_collection", (DL_FUNC) &c_cudd_disable_garbage_collection, 1},
    {"c_cudd_dead_are_counted", (DL_FUNC) &c_cudd_dead_are_counted, 1},
    {"c_cudd_turn_on_count_dead", (DL_FUNC) &c_cudd_turn_on_count_dead, 1},
    {"c_cudd_turn_off_count_dead", (DL_FUNC) &c_cudd_turn_off_count_dead, 1},
    {"c_cudd_read_recomb", (DL_FUNC) &c_cudd_read_recomb, 1},
    {"c_cudd_set_recomb", (DL_FUNC) &c_cudd_set_recomb, 2},
    {"c_cudd_read_symmviolation", (DL_FUNC) &c_cudd_read_symmviolation, 1},
    {"c_cudd_set_symmviolation", (DL_FUNC) &c_cudd_set_symmviolation, 2},
    {"c_cudd_read_arcviolation", (DL_FUNC) &c_cudd_read_arcviolation, 1},
    {"c_cudd_set_arcviolation", (DL_FUNC) &c_cudd_set_arcviolation, 2},
    {"c_cudd_read_population_size", (DL_FUNC) &c_cudd_read_population_size, 1},
    {"c_cudd_set_population_size", (DL_FUNC) &c_cudd_set_population_size, 2},
    {"c_cudd_read_number_xovers", (DL_FUNC) &c_cudd_read_number_xovers, 1},
    {"c_cudd_set_number_xovers", (DL_FUNC) &c_cudd_set_number_xovers, 2},
    {"c_cudd_read_order_randomization", (DL_FUNC) &c_cudd_read_order_randomization, 1},
    {"c_cudd_set_order_randomization", (DL_FUNC) &c_cudd_set_order_randomization, 2},
    {"c_cudd_read_memory_in_use", (DL_FUNC) &c_cudd_read_memory_in_use, 1},
    {"c_cudd_read_peak_node_count", (DL_FUNC) &c_cudd_read_peak_node_count, 1},
    {"c_cudd_read_node_count_current", (DL_FUNC) &c_cudd_read_node_count_current, 1},
    {"c_cudd_read_node_count_zdd", (DL_FUNC) &c_cudd_read_node_count_zdd, 1},
    {"c_cudd_enable_reordering_reporting", (DL_FUNC) &c_cudd_enable_reordering_reporting, 1},
    {"c_cudd_disable_reordering_reporting", (DL_FUNC) &c_cudd_disable_reordering_reporting, 1},
    {"c_cudd_reordering_reporting", (DL_FUNC) &c_cudd_reordering_reporting, 1},
    {"c_cudd_read_error_code", (DL_FUNC) &c_cudd_read_error_code, 1},
    {"c_cudd_clear_error_code", (DL_FUNC) &c_cudd_clear_error_code, 1},
    {"c_cudd_read_next_reordering", (DL_FUNC) &c_cudd_read_next_reordering, 1},
    {"c_cudd_set_next_reordering", (DL_FUNC) &c_cudd_set_next_reordering, 2},
    {"c_cudd_read_swap_steps", (DL_FUNC) &c_cudd_read_swap_steps, 1},
    {"c_cudd_read_max_live", (DL_FUNC) &c_cudd_read_max_live, 1},
    {"c_cudd_set_max_live", (DL_FUNC) &c_cudd_set_max_live, 2},
    {"c_cudd_read_max_memory", (DL_FUNC) &c_cudd_read_max_memory, 1},
    {"c_cudd_set_max_memory", (DL_FUNC) &c_cudd_set_max_memory, 2},
    {"c_cudd_bdd_bind_var", (DL_FUNC) &c_cudd_bdd_bind_var, 2},
    {"c_cudd_bdd_unbind_var", (DL_FUNC) &c_cudd_bdd_unbind_var, 2},
    {"c_cudd_bdd_var_is_bound", (DL_FUNC) &c_cudd_bdd_var_is_bound, 2},
    {"c_bdd_remaining_literals", (DL_FUNC) &bdd_remaining_literals, 1},
    {"c_bdd_restrict_chain", (DL_FUNC) &bdd_restrict_chain, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_Rcudd(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    R_forceSymbols(dll, TRUE);
}
